apiVersion: apps/v1
kind: Deployment
metadata:
  name: okmi5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okmi5
  template:
    metadata:
      labels:
        app: okmi5
    spec:
      containers:
      - image: okteto.dev/okmi5:latest
        name: okmi5
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: ParameterSSENCYPT
          value: "chacha20-ietf-poly1305"
        - name: AUUID
          value: "efd77f7a-ad6f-4ae9-8d75-00183270c4bf"
