apiVersion: v1
kind: Service
metadata:
  name: okmi5
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "okmi5"
    port: 8080
  selector:
    app: okmi5
